/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#d7e2ff",
        "on-secondary": "#003824",
        "on-primary": "#002f66",
        "surface-container": "#171f33",
        "inverse-on-surface": "#283044",
        "on-background": "#dae2fd",
        "on-tertiary": "#472a00",
        "outline-variant": "#424752",
        "error-container": "#93000a",
        "on-surface-variant": "#c2c6d4",
        "background": "#0b1326",
        "surface-variant": "#2d3449",
        "primary-container": "#2e72d2",
        "primary-fixed-dim": "#abc7ff",
        "inverse-surface": "#dae2fd",
        "secondary-container": "#00a572",
        "tertiary-container": "#a26600",
        "surface-dim": "#0b1326",
        "outline": "#8c919e",
        "tertiary-fixed-dim": "#ffb95f",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#005cbb",
        "on-primary-fixed-variant": "#00458f",
        "surface-tint": "#abc7ff",
        "on-secondary-fixed": "#002113",
        "on-secondary-container": "#00311f",
        "on-tertiary-fixed": "#2a1700",
        "tertiary": "#ffb95f",
        "tertiary-fixed": "#ffddb8",
        "on-primary-fixed": "#001b3f",
        "surface": "#0b1326",
        "secondary-fixed": "#6ffbbe",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "surface-bright": "#31394d",
        "primary": "#abc7ff",
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "surface-container-highest": "#2d3449",
        "secondary": "#4edea3",
        "on-tertiary-container": "#fff9f7",
        "surface-container-high": "#222a3d",
        "on-surface": "#dae2fd",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary-container": "#fbfaff",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-fixed-variant": "#005236"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "1px",
        "sidebar-width": "260px",
        "lg": "24px",
        "sm": "8px",
        "unit": "4px",
        "activity-bar-width": "48px",
        "md": "16px",
        "xl": "32px",
        "xs": "4px"
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "label-caps": ["Inter", "sans-serif"],
        "code-base": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
